/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author elavincho
 */
public class Calculadora extends javax.swing.JFrame {
    private String cadenaNumeros = "";
    private String operacion = "vacia";
    private double primerNumero, resultado;
    private boolean activado = true;
    private boolean punto = true;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonC = new javax.swing.JButton();
        botonRaiz = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        botonCE = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonMultiplicacion = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        botonCambioSigno = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        pantallaResultado = new javax.swing.JLabel();
        pantallaOperacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        botonC.setBackground(new java.awt.Color(102, 102, 102));
        botonC.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        jPanel1.add(botonC);

        botonRaiz.setBackground(new java.awt.Color(102, 102, 102));
        botonRaiz.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonRaiz.setText("√");
        botonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizActionPerformed(evt);
            }
        });
        jPanel1.add(botonRaiz);

        botonDivision.setBackground(new java.awt.Color(102, 102, 102));
        botonDivision.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonDivision.setText("/");
        botonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(botonDivision);

        botonCE.setBackground(new java.awt.Color(102, 102, 102));
        botonCE.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonCE.setText("CE");
        botonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCEActionPerformed(evt);
            }
        });
        jPanel1.add(botonCE);

        boton7.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        jPanel1.add(boton7);

        boton8.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        jPanel1.add(boton8);

        boton9.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        jPanel1.add(boton9);

        botonMultiplicacion.setBackground(new java.awt.Color(102, 102, 102));
        botonMultiplicacion.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonMultiplicacion.setText("X");
        botonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(botonMultiplicacion);

        boton4.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        jPanel1.add(boton4);

        boton5.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        jPanel1.add(boton5);

        boton6.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        jPanel1.add(boton6);

        botonResta.setBackground(new java.awt.Color(102, 102, 102));
        botonResta.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonResta.setText("-");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta);

        boton1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1);

        boton2.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2);

        boton3.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(boton3);

        botonSuma.setBackground(new java.awt.Color(102, 102, 102));
        botonSuma.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonSuma.setText("+");
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });
        jPanel1.add(botonSuma);

        botonCambioSigno.setBackground(new java.awt.Color(102, 102, 102));
        botonCambioSigno.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonCambioSigno.setText("+/-");
        jPanel1.add(botonCambioSigno);

        boton0.setBackground(new java.awt.Color(102, 102, 102));
        boton0.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        jPanel1.add(boton0);

        botonPunto.setBackground(new java.awt.Color(102, 102, 102));
        botonPunto.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        jPanel1.add(botonPunto);

        botonIgual.setBackground(new java.awt.Color(102, 102, 102));
        botonIgual.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        jPanel1.add(botonIgual);

        pantallaResultado.setBackground(new java.awt.Color(255, 255, 255));
        pantallaResultado.setFont(new java.awt.Font("Zurich Ex BT", 0, 36)); // NOI18N
        pantallaResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantallaResultado.setText("0");

        pantallaOperacion.setBackground(new java.awt.Color(255, 255, 255));
        pantallaOperacion.setFont(new java.awt.Font("Zurich Ex BT", 0, 14)); // NOI18N
        pantallaOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pantallaOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pantallaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantallaOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantallaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "8";
        }else {
            cadenaNumeros += "8";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton8ActionPerformed

    private void botonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicacionActionPerformed
        // TODO add your handling code here:
        if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            pantallaOperacion.setText(cadenaNumeros + " x ");
            cadenaNumeros = "";
            operacion = "multiplicar";
            activado = false;
        }
                 

    }//GEN-LAST:event_botonMultiplicacionActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "7";
        }else {
            cadenaNumeros += "7";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "9";
        }else {
            cadenaNumeros += "9";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "4";
        }else {
            cadenaNumeros += "4";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "5";
        }else {
            cadenaNumeros += "5";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "6";
        }else {
            cadenaNumeros += "6";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "1";
        }else {
            cadenaNumeros += "1";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "2";
        }else {
            cadenaNumeros += "2";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "3";
        }else {
            cadenaNumeros += "3";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        // TODO add your handling code here:
        if(pantallaResultado.getText().equals("0")) {
            cadenaNumeros = "0";
        }else {
            cadenaNumeros += "0";
        }
        pantallaResultado.setText(cadenaNumeros);
        activado = true; // voy a usar la calculadora
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        // TODO add your handling code here:
        pantallaResultado.setText("0");
    }//GEN-LAST:event_botonCActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        // TODO add your handling code here:
        if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            pantallaOperacion.setText(cadenaNumeros + " + ");
            cadenaNumeros = "";
            operacion = "sumar";
            activado = false;
        }
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        // TODO add your handling code here:
        double segundoNumero;
        
        if (operacion.equals("sumar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero + segundoNumero;
            pantallaResultado.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "+";
            pantallaOperacion.setText(primerNumero + "" + operacion + "" + segundoNumero);
        }
        
        activado = true;
        
        if (operacion.equals("restar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero - segundoNumero;
            pantallaResultado.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "vacia";
            pantallaOperacion.setText("");
        }
        
        activado = true;
        
        if (operacion.equals("multiplicar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * segundoNumero;
            pantallaResultado.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "vacia";
            pantallaOperacion.setText("");
        }
        
        activado = true;
        
        if (operacion.equals("dividir")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero / segundoNumero;
            pantallaResultado.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "vacia";
            pantallaOperacion.setText("");
        }
        
        activado = true;
        
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        // TODO add your handling code here:
        if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            pantallaOperacion.setText(cadenaNumeros + " - ");
            cadenaNumeros = "";
            operacion = "restar";
            activado = false;
        }
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivisionActionPerformed
        // TODO add your handling code here:
        if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            pantallaOperacion.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
            operacion = "dividir";
            activado = false;
        }
    }//GEN-LAST:event_botonDivisionActionPerformed

    private void botonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizActionPerformed
        // TODO add your handling code here:
        
            primerNumero = Double.parseDouble(cadenaNumeros);
            pantallaOperacion.setText("sqrt(" + cadenaNumeros + ")");
            resultado = Math.sqrt(primerNumero);
            pantallaResultado.setText(String.format("%.2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            activado = false;
        
    }//GEN-LAST:event_botonRaizActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        // TODO add your handling code here:
        if (punto == true) {
            if (cadenaNumeros.equals("")){
                cadenaNumeros = "0.";
                
            }else {
                cadenaNumeros += ".";
            }
            
        }
        punto = false;
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCEActionPerformed
        // TODO add your handling code here:
        int tamano = cadenaNumeros.length();
        if (tamano > 0) {
            if (tamano == 1) {
                cadenaNumeros = "0";
            }else {
                cadenaNumeros = cadenaNumeros.substring(0, (cadenaNumeros.length() - 1));
            }
            pantallaResultado.setText(cadenaNumeros);
        }
        
    }//GEN-LAST:event_botonCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonCE;
    private javax.swing.JButton botonCambioSigno;
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMultiplicacion;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRaiz;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pantallaOperacion;
    private javax.swing.JLabel pantallaResultado;
    // End of variables declaration//GEN-END:variables
}
